// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdmxtmihlqukfgtdjrce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbXh0bWlobHF1a2ZndGRqcmNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDY5NjUsImV4cCI6MjA2NTMyMjk2NX0.1FY8h59N1hm8BVaUFhBzyqGlafRn29pKMKGUC9F3SOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);